// <auto-generated />
using System;
using BenhaScooters.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BenhaScooters.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250810213537_Driver_Onb_Status")]
    partial class Driver_Onb_Status
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BenhaScooters.Domain.Drivers.Driver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Drivers");
                });

            modelBuilder.Entity("BenhaScooters.Domain.Drivers.DriverAvailability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CurrentTripId")
                        .HasColumnType("integer");

                    b.Property<int>("DriverId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastStatusChange")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("OnlineSessionStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeSpan>("TotalOnlineTime")
                        .HasColumnType("interval");

                    b.HasKey("Id");

                    b.HasIndex("CurrentTripId");

                    b.HasIndex("Status");

                    b.ToTable("DriverAvailabilities");
                });

            modelBuilder.Entity("BenhaScooters.Domain.Drivers.DriverLocation", b =>
                {
                    b.Property<int>("DriverId")
                        .HasColumnType("integer");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geography (point)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("DriverId");

                    b.HasIndex("Location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "GIST");

                    b.HasIndex("Timestamp");

                    b.ToTable("DriverLocations");
                });

            modelBuilder.Entity("BenhaScooters.Domain.Drivers.DriverRating", b =>
                {
                    b.Property<int>("DriverId")
                        .HasColumnType("integer");

                    b.Property<decimal>("AverageRating")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TotalRatings")
                        .HasColumnType("integer");

                    b.HasKey("DriverId");

                    b.ToTable("DriverRatings");
                });

            modelBuilder.Entity("BenhaScooters.Domain.Drivers.Entities.DriverDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DriverId")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.ToTable("DriverDocument");
                });

            modelBuilder.Entity("BenhaScooters.Domain.Drivers.Entities.DriverVehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeactivatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DriverId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("VIN")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("character varying(17)");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DriverId")
                        .IsUnique();

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("BenhaScooters.Domain.Matching.DriverMatchAttempt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("DistanceToPickup")
                        .HasPrecision(8, 3)
                        .HasColumnType("double precision");

                    b.Property<int>("DriverId")
                        .HasColumnType("integer");

                    b.Property<decimal>("DriverScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<double>("EstimatedArrivalTime")
                        .HasPrecision(5, 2)
                        .HasColumnType("double precision");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MatchingSessionId")
                        .HasColumnType("integer");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("DriverId");

                    b.HasIndex("MatchingSessionId");

                    b.HasIndex("Status");

                    b.ToTable("DriverMatchAttempts");
                });

            modelBuilder.Entity("BenhaScooters.Domain.Matching.MatchingSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentRound")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NumberOfRounds")
                        .HasColumnType("integer");

                    b.Property<string>("OffersPerRound")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TripRequestId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Status");

                    b.HasIndex("TripRequestId")
                        .IsUnique();

                    b.ToTable("MatchingSessions");
                });

            modelBuilder.Entity("BenhaScooters.Domain.Riders.Rider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DefaultPaymentMethodId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastTripAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PreferredName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SavedAddresses")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalTrips")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Riders");
                });

            modelBuilder.Entity("BenhaScooters.Domain.TripRequests.TripRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("DropoffAddress")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Point>("DropoffLocation")
                        .IsRequired()
                        .HasColumnType("geography (point)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("MatchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("MatchedDriverId")
                        .HasColumnType("integer");

                    b.Property<string>("PickupAddress")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Point>("PickupLocation")
                        .IsRequired()
                        .HasColumnType("geography (point)");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RiderId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MatchedDriverId");

                    b.HasIndex("RequestedAt");

                    b.HasIndex("RiderId");

                    b.HasIndex("Status");

                    b.ToTable("TripRequests");
                });

            modelBuilder.Entity("BenhaScooters.Domain.Trips.Trip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DriverArrivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DriverId")
                        .HasColumnType("integer");

                    b.Property<string>("DropoffAddress")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Point>("DropoffLocation")
                        .IsRequired()
                        .HasColumnType("geography (point)");

                    b.Property<string>("PickupAddress")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Point>("PickupLocation")
                        .IsRequired()
                        .HasColumnType("geography (point)");

                    b.Property<int>("RiderId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("RiderId");

                    b.HasIndex("Status");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("BenhaScooters.Domain.Trips.TripGpsPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geography (point)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TripId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "GIST");

                    b.HasIndex("Timestamp");

                    b.HasIndex("TripId");

                    b.ToTable("TripGpsPoints");
                });

            modelBuilder.Entity("BenhaScooters.Domain.Trips.TripRoute", b =>
                {
                    b.Property<int>("TripId")
                        .HasColumnType("integer");

                    b.Property<LineString>("Path")
                        .IsRequired()
                        .HasColumnType("geometry (LineString, 4326)");

                    b.HasKey("TripId");

                    b.ToTable("TripRoutes", (string)null);
                });

            modelBuilder.Entity("BenhaScooters.Domain.Users.ExternalAuth", b =>
                {
                    b.Property<string>("Provider")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ProviderUserId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Provider", "ProviderUserId");

                    b.HasIndex("UserId");

                    b.ToTable("ExternalAuths", (string)null);
                });

            modelBuilder.Entity("BenhaScooters.Domain.Users.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("BenhaScooters.Domain.Users.SmsVerificationCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Code");

                    b.HasIndex("UserId", "PhoneNumber", "CreatedAt");

                    b.ToTable("SmsVerificationCodes");
                });

            modelBuilder.Entity("BenhaScooters.Domain.Users.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EmailNormalized")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PhoneNumberNormalized")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("PhoneNumberVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EmailNormalized");

                    b.HasIndex("PhoneNumberNormalized");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BenhaScooters.Domain.Users.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("BenhaScooters.Domain.Drivers.Driver", b =>
                {
                    b.HasOne("BenhaScooters.Domain.Users.User", null)
                        .WithOne()
                        .HasForeignKey("BenhaScooters.Domain.Drivers.Driver", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("BenhaScooters.Domain.Drivers.ValueObjects.DriverInfo", "Info", b1 =>
                        {
                            b1.Property<int>("DriverId")
                                .HasColumnType("integer");

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<DateOnly>("DateOfBirth")
                                .HasColumnType("date");

                            b1.Property<string>("EmergencyContactName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<string>("EmergencyContactPhone")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("FullName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<string>("NationalId")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("DriverId");

                            b1.HasIndex("NationalId")
                                .IsUnique();

                            b1.ToTable("Drivers");

                            b1.WithOwner()
                                .HasForeignKey("DriverId");
                        });

                    b.OwnsOne("BenhaScooters.Domain.Drivers.ValueObjects.OnboardingState", "OnboardingState", b1 =>
                        {
                            b1.Property<int>("DriverId")
                                .HasColumnType("integer");

                            b1.Property<DateTime?>("CompletedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("RejectionReason")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("DriverId");

                            b1.ToTable("Drivers");

                            b1.WithOwner()
                                .HasForeignKey("DriverId");
                        });

                    b.Navigation("Info");

                    b.Navigation("OnboardingState")
                        .IsRequired();
                });

            modelBuilder.Entity("BenhaScooters.Domain.Drivers.DriverAvailability", b =>
                {
                    b.HasOne("BenhaScooters.Domain.Trips.Trip", null)
                        .WithMany()
                        .HasForeignKey("CurrentTripId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("BenhaScooters.Domain.Drivers.DriverLocation", b =>
                {
                    b.HasOne("BenhaScooters.Domain.Drivers.Driver", "Driver")
                        .WithOne()
                        .HasForeignKey("BenhaScooters.Domain.Drivers.DriverLocation", "DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("BenhaScooters.Domain.Drivers.DriverRating", b =>
                {
                    b.HasOne("BenhaScooters.Domain.Drivers.Driver", "Driver")
                        .WithOne()
                        .HasForeignKey("BenhaScooters.Domain.Drivers.DriverRating", "DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("BenhaScooters.Domain.Drivers.Entities.DriverDocument", b =>
                {
                    b.HasOne("BenhaScooters.Domain.Drivers.Driver", "Driver")
                        .WithMany("Documents")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("BenhaScooters.Domain.Drivers.Entities.DriverVehicle", b =>
                {
                    b.HasOne("BenhaScooters.Domain.Drivers.Driver", "Driver")
                        .WithOne("Vehicle")
                        .HasForeignKey("BenhaScooters.Domain.Drivers.Entities.DriverVehicle", "DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("BenhaScooters.Domain.Matching.DriverMatchAttempt", b =>
                {
                    b.HasOne("BenhaScooters.Domain.Drivers.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BenhaScooters.Domain.Matching.MatchingSession", "MatchingSession")
                        .WithMany("MatchAttempts")
                        .HasForeignKey("MatchingSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("MatchingSession");
                });

            modelBuilder.Entity("BenhaScooters.Domain.Matching.MatchingSession", b =>
                {
                    b.HasOne("BenhaScooters.Domain.TripRequests.TripRequest", "TripRequest")
                        .WithMany()
                        .HasForeignKey("TripRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TripRequest");
                });

            modelBuilder.Entity("BenhaScooters.Domain.Riders.Rider", b =>
                {
                    b.HasOne("BenhaScooters.Domain.Users.User", "User")
                        .WithOne()
                        .HasForeignKey("BenhaScooters.Domain.Riders.Rider", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("BenhaScooters.Domain.Riders.ValueObjects.RiderRating", "Rating", b1 =>
                        {
                            b1.Property<int>("RiderId")
                                .HasColumnType("integer");

                            b1.Property<decimal>("Rating")
                                .HasColumnType("numeric");

                            b1.Property<int>("TotalRatings")
                                .HasColumnType("integer");

                            b1.HasKey("RiderId");

                            b1.ToTable("Riders");

                            b1.WithOwner()
                                .HasForeignKey("RiderId");
                        });

                    b.Navigation("Rating")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BenhaScooters.Domain.TripRequests.TripRequest", b =>
                {
                    b.HasOne("BenhaScooters.Domain.Drivers.Driver", "MatchedDriver")
                        .WithMany()
                        .HasForeignKey("MatchedDriverId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BenhaScooters.Domain.Riders.Rider", "Rider")
                        .WithMany()
                        .HasForeignKey("RiderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("BenhaScooters.Domain.Trips.ValueObjects.FareEstimate", "EstimatedFare", b1 =>
                        {
                            b1.Property<int>("TripRequestId")
                                .HasColumnType("integer");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric");

                            b1.Property<double>("Distance")
                                .HasColumnType("double precision");

                            b1.Property<double>("Time")
                                .HasColumnType("double precision");

                            b1.HasKey("TripRequestId");

                            b1.ToTable("TripRequests");

                            b1.WithOwner()
                                .HasForeignKey("TripRequestId");
                        });

                    b.Navigation("EstimatedFare")
                        .IsRequired();

                    b.Navigation("MatchedDriver");

                    b.Navigation("Rider");
                });

            modelBuilder.Entity("BenhaScooters.Domain.Trips.Trip", b =>
                {
                    b.HasOne("BenhaScooters.Domain.Drivers.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BenhaScooters.Domain.Riders.Rider", "Rider")
                        .WithMany()
                        .HasForeignKey("RiderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("BenhaScooters.Domain.Trips.ValueObjects.FareEstimate", "EstimatedFare", b1 =>
                        {
                            b1.Property<int>("TripId")
                                .HasColumnType("integer");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<double>("Distance")
                                .HasColumnType("double precision");

                            b1.Property<double>("Time")
                                .HasColumnType("double precision");

                            b1.HasKey("TripId");

                            b1.ToTable("Trips");

                            b1.WithOwner()
                                .HasForeignKey("TripId");
                        });

                    b.OwnsOne("BenhaScooters.Domain.Trips.ValueObjects.TripFare", "TripFare", b1 =>
                        {
                            b1.Property<int>("TripId")
                                .HasColumnType("integer");

                            b1.Property<decimal>("BaseFare")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<decimal>("DistanceFare")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<decimal>("DurationFare")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<decimal>("SurgeMultiplier")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("TotalFare")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("TotalFare");

                            b1.HasKey("TripId");

                            b1.ToTable("Trips");

                            b1.WithOwner()
                                .HasForeignKey("TripId");
                        });

                    b.OwnsOne("BenhaScooters.Domain.Trips.ValueObjects.TripPayment", "TripPayment", b1 =>
                        {
                            b1.Property<int>("TripId")
                                .HasColumnType("integer");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<string>("ExternalReference")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<string>("Method")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<decimal>("PaidAmount")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("TripId");

                            b1.ToTable("Trips");

                            b1.WithOwner()
                                .HasForeignKey("TripId");
                        });

                    b.Navigation("Driver");

                    b.Navigation("EstimatedFare")
                        .IsRequired();

                    b.Navigation("Rider");

                    b.Navigation("TripFare");

                    b.Navigation("TripPayment");
                });

            modelBuilder.Entity("BenhaScooters.Domain.Trips.TripGpsPoint", b =>
                {
                    b.HasOne("BenhaScooters.Domain.Trips.TripRoute", "TripRoute")
                        .WithMany("TripGpsPoints")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TripRoute");
                });

            modelBuilder.Entity("BenhaScooters.Domain.Trips.TripRoute", b =>
                {
                    b.HasOne("BenhaScooters.Domain.Trips.Trip", "Trip")
                        .WithOne()
                        .HasForeignKey("BenhaScooters.Domain.Trips.TripRoute", "TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("BenhaScooters.Domain.Users.ExternalAuth", b =>
                {
                    b.HasOne("BenhaScooters.Domain.Users.User", "User")
                        .WithMany("ExternalAuths")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BenhaScooters.Domain.Users.RefreshToken", b =>
                {
                    b.HasOne("BenhaScooters.Domain.Users.User", null)
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BenhaScooters.Domain.Users.SmsVerificationCode", b =>
                {
                    b.HasOne("BenhaScooters.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BenhaScooters.Domain.Users.UserRole", b =>
                {
                    b.HasOne("BenhaScooters.Domain.Users.User", null)
                        .WithMany("Roles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BenhaScooters.Domain.Drivers.Driver", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("BenhaScooters.Domain.Matching.MatchingSession", b =>
                {
                    b.Navigation("MatchAttempts");
                });

            modelBuilder.Entity("BenhaScooters.Domain.Trips.TripRoute", b =>
                {
                    b.Navigation("TripGpsPoints");
                });

            modelBuilder.Entity("BenhaScooters.Domain.Users.User", b =>
                {
                    b.Navigation("ExternalAuths");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
