// <auto-generated />
using System;
using System.Collections.Generic;
using BenhaScooters.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BenhaScooters.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260402130637_AddUserPreferredLanguage")]
    partial class AddUserPreferredLanguage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BenhaScooters.Domain.Drivers.DriverLocation", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<float?>("Heading")
                        .HasColumnType("real");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geography (point)");

                    b.Property<float?>("Speed")
                        .HasColumnType("real");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId");

                    b.HasIndex("Location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "GIST");

                    b.HasIndex("Timestamp");

                    b.ToTable("DriverLocations", (string)null);
                });

            modelBuilder.Entity("BenhaScooters.Domain.Drivers.DriverProfile", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OnboardingStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("UserId");

                    b.HasIndex("OnboardingStatus");

                    b.ToTable("DriverProfiles", (string)null);
                });

            modelBuilder.Entity("BenhaScooters.Domain.Drivers.DriverStats", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<decimal>("AverageRating")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)");

                    b.Property<int>("CancelledTrips")
                        .HasColumnType("integer");

                    b.Property<int>("CompletedTrips")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentStreak")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastOnlineAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastStreakDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastTripAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan>("TotalOnlineTime")
                        .HasColumnType("interval");

                    b.Property<int>("TotalRatings")
                        .HasColumnType("integer");

                    b.Property<int>("TotalTrips")
                        .HasColumnType("integer");

                    b.HasKey("UserId");

                    b.HasIndex("AverageRating");

                    b.HasIndex("CompletedTrips");

                    b.ToTable("DriverStats", (string)null);
                });

            modelBuilder.Entity("BenhaScooters.Domain.Drivers.DriverStatus", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int?>("CurrentTripId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastHeartbeat")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastStatusChange")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("OnlineSessionStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.HasIndex("Status");

                    b.HasIndex("Status", "UserId");

                    b.ToTable("DriverStatuses", (string)null);
                });

            modelBuilder.Entity("BenhaScooters.Domain.Drivers.DriverWallet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DriverUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DriverUserId")
                        .IsUnique();

                    b.ToTable("DriverWallets", (string)null);
                });

            modelBuilder.Entity("BenhaScooters.Domain.Drivers.WalletTopUpRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DriverUserId")
                        .HasColumnType("integer");

                    b.Property<string>("ReceiptUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ReviewNote")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ReviewedByUserId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("WalletId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("DriverUserId");

                    b.HasIndex("Status");

                    b.HasIndex("WalletId");

                    b.ToTable("WalletTopUpRequests", (string)null);
                });

            modelBuilder.Entity("BenhaScooters.Domain.Drivers.WalletTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("BalanceAfter")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("DescriptionKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DescriptionParams")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int?>("TripId")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("WalletId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("TripId");

                    b.HasIndex("WalletId");

                    b.ToTable("WalletTransactions", (string)null);
                });

            modelBuilder.Entity("BenhaScooters.Domain.Matching.DriverMatchAttempt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("DistanceToPickup")
                        .HasColumnType("double precision");

                    b.Property<decimal>("DriverScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<int>("DriverUserId")
                        .HasColumnType("integer");

                    b.Property<double>("EstimatedArrivalTime")
                        .HasColumnType("double precision");

                    b.Property<int>("MatchingRound")
                        .HasColumnType("integer");

                    b.Property<int>("MatchingSessionId")
                        .HasColumnType("integer");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("DriverUserId");

                    b.HasIndex("MatchingSessionId");

                    b.HasIndex("Status");

                    b.ToTable("DriverMatchAttempts");
                });

            modelBuilder.Entity("BenhaScooters.Domain.Matching.MatchingSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentRound")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NumberOfRounds")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<int[]>("OffersPerRound")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TripRequestId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Status");

                    b.HasIndex("TripRequestId")
                        .IsUnique();

                    b.ToTable("MatchingSessions");
                });

            modelBuilder.Entity("BenhaScooters.Domain.Ratings.DriverRating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DriverId")
                        .HasColumnType("integer");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<int>("RiderId")
                        .HasColumnType("integer");

                    b.Property<int>("TripId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("TripId", "RiderId")
                        .IsUnique();

                    b.ToTable("DriverRatings", (string)null);
                });

            modelBuilder.Entity("BenhaScooters.Domain.Riders.RiderProfile", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<decimal>("AverageRating")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DefaultPaymentMethodId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastTripAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PreferredName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("TotalRatings")
                        .HasColumnType("integer");

                    b.Property<int>("TotalTrips")
                        .HasColumnType("integer");

                    b.HasKey("UserId");

                    b.ToTable("RiderProfiles", (string)null);
                });

            modelBuilder.Entity("BenhaScooters.Domain.ServiceAreas.ServiceArea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<MultiPolygon>("Area")
                        .IsRequired()
                        .HasColumnType("geometry(MultiPolygon, 4326)");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.ToTable("ServiceAreas");
                });

            modelBuilder.Entity("BenhaScooters.Domain.TripRequests.TripRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DropoffAddress")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Point>("DropoffLocation")
                        .IsRequired()
                        .HasColumnType("geography (point)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("MatchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("MatchedDriverId")
                        .HasColumnType("integer");

                    b.Property<string>("PickupAddress")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Point>("PickupLocation")
                        .IsRequired()
                        .HasColumnType("geography (point)");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RiderId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ComplexProperty<Dictionary<string, object>>("FinalFare", "BenhaScooters.Domain.TripRequests.TripRequest.FinalFare#FareEstimate", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("FinalFare_Amount");

                            b1.Property<double>("Distance")
                                .HasColumnType("double precision")
                                .HasColumnName("FinalFare_Distance");

                            b1.Property<double>("Time")
                                .HasColumnType("double precision")
                                .HasColumnName("FinalFare_Time");
                        });

                    b.HasKey("Id");

                    b.HasIndex("MatchedDriverId");

                    b.HasIndex("RequestedAt");

                    b.HasIndex("RiderId");

                    b.HasIndex("Status");

                    b.ToTable("TripRequests");
                });

            modelBuilder.Entity("BenhaScooters.Domain.Trips.Trip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DriverArrivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DriverId")
                        .HasColumnType("integer");

                    b.Property<string>("DropoffAddress")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Point>("DropoffLocation")
                        .IsRequired()
                        .HasColumnType("geography (point)");

                    b.Property<string>("PickupAddress")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Point>("PickupLocation")
                        .IsRequired()
                        .HasColumnType("geography (point)");

                    b.Property<int>("RiderId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TripRequestId")
                        .HasColumnType("integer");

                    b.ComplexProperty<Dictionary<string, object>>("FinalFare", "BenhaScooters.Domain.Trips.Trip.FinalFare#FareEstimate", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("FinalFare_Amount");

                            b1.Property<double>("Distance")
                                .HasColumnType("double precision")
                                .HasColumnName("FinalFare_Distance");

                            b1.Property<double>("Time")
                                .HasColumnType("double precision")
                                .HasColumnName("FinalFare_Time");
                        });

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("RiderId");

                    b.HasIndex("Status");

                    b.HasIndex("TripRequestId")
                        .IsUnique();

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("BenhaScooters.Domain.Trips.TripGpsPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geography (point)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TripId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "GIST");

                    b.HasIndex("Timestamp");

                    b.HasIndex("TripId");

                    b.ToTable("TripGpsPoints");
                });

            modelBuilder.Entity("BenhaScooters.Domain.Trips.TripRoute", b =>
                {
                    b.Property<int>("TripId")
                        .HasColumnType("integer");

                    b.Property<LineString>("Path")
                        .IsRequired()
                        .HasColumnType("geometry (LineString, 4326)");

                    b.HasKey("TripId");

                    b.ToTable("TripRoutes", (string)null);
                });

            modelBuilder.Entity("BenhaScooters.Domain.Users.ExternalAuth", b =>
                {
                    b.Property<string>("Provider")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ProviderUserId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Provider", "ProviderUserId");

                    b.HasIndex("UserId");

                    b.ToTable("ExternalAuths", (string)null);
                });

            modelBuilder.Entity("BenhaScooters.Domain.Users.OtpSecurityEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("Metadata")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IpAddress", "EventType", "CreatedAt");

                    b.HasIndex("PhoneNumber", "EventType", "CreatedAt");

                    b.HasIndex("UserId", "EventType", "CreatedAt");

                    b.ToTable("OtpSecurityEvents");
                });

            modelBuilder.Entity("BenhaScooters.Domain.Users.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("BenhaScooters.Domain.Users.SmsLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Cost")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("cost");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered_at");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("error_message");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("message");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_number");

                    b.Property<string>("ProviderId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("provider_id");

                    b.Property<string>("ProviderUid")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("provider_uid");

                    b.Property<int>("SmsCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("sms_count");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_sms_logs_created_at");

                    b.HasIndex("PhoneNumber")
                        .HasDatabaseName("ix_sms_logs_phone_number");

                    b.HasIndex("ProviderId")
                        .HasDatabaseName("ix_sms_logs_provider_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_sms_logs_status");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_sms_logs_user_id");

                    b.ToTable("sms_logs", (string)null);
                });

            modelBuilder.Entity("BenhaScooters.Domain.Users.SmsVerificationCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FailedAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LockedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "IsUsed", "ExpiresAt");

                    b.HasIndex("UserId", "PhoneNumber", "CreatedAt");

                    b.ToTable("SmsVerificationCodes");
                });

            modelBuilder.Entity("BenhaScooters.Domain.Users.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("PhoneNumberVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("PreferredLanguage")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("PhoneNumber");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BenhaScooters.Domain.Users.UserDeviceToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Token");

                    b.HasIndex("UserId", "Platform")
                        .IsUnique();

                    b.ToTable("UserDeviceTokens", (string)null);
                });

            modelBuilder.Entity("BenhaScooters.Domain.Users.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("BenhaScooters.Domain.Drivers.DriverLocation", b =>
                {
                    b.HasOne("BenhaScooters.Domain.Users.User", "User")
                        .WithOne()
                        .HasForeignKey("BenhaScooters.Domain.Drivers.DriverLocation", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BenhaScooters.Domain.Drivers.DriverProfile", b =>
                {
                    b.HasOne("BenhaScooters.Domain.Users.User", "User")
                        .WithOne("DriverProfile")
                        .HasForeignKey("BenhaScooters.Domain.Drivers.DriverProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("BenhaScooters.Domain.Drivers.DriverPersonalInfo", "PersonalInfo", b1 =>
                        {
                            b1.Property<int>("DriverProfileUserId")
                                .HasColumnType("integer");

                            b1.Property<string>("FullName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("PersonalInfo_FullName");

                            b1.Property<string>("NationalId")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("PersonalInfo_NationalId");

                            b1.HasKey("DriverProfileUserId");

                            b1.ToTable("DriverProfiles");

                            b1.WithOwner()
                                .HasForeignKey("DriverProfileUserId");
                        });

                    b.OwnsOne("BenhaScooters.Domain.Drivers.DriverVehicleInfo", "Vehicle", b1 =>
                        {
                            b1.Property<int>("DriverProfileUserId")
                                .HasColumnType("integer");

                            b1.Property<string>("Brand")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("Vehicle_Brand");

                            b1.Property<string>("Color")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("Vehicle_Color");

                            b1.Property<string>("LicensePlate")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Vehicle_LicensePlate");

                            b1.Property<string>("Model")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("Vehicle_Model");

                            b1.Property<string>("VehicleType")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Vehicle_Type");

                            b1.Property<int>("Year")
                                .HasColumnType("integer")
                                .HasColumnName("Vehicle_Year");

                            b1.HasKey("DriverProfileUserId");

                            b1.ToTable("DriverProfiles");

                            b1.WithOwner()
                                .HasForeignKey("DriverProfileUserId");
                        });

                    b.OwnsMany("BenhaScooters.Domain.Drivers.DriverDocument", "Documents", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<int>("DriverUserId")
                                .HasColumnType("integer");

                            b1.Property<DateOnly?>("ExpiryDate")
                                .HasColumnType("date");

                            b1.Property<string>("ImageUrl")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<DateTime>("UploadedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("Id");

                            b1.HasIndex("DriverUserId", "Type")
                                .IsUnique();

                            b1.ToTable("DriverDocuments", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("DriverUserId");
                        });

                    b.Navigation("Documents");

                    b.Navigation("PersonalInfo");

                    b.Navigation("User");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("BenhaScooters.Domain.Drivers.DriverStats", b =>
                {
                    b.HasOne("BenhaScooters.Domain.Users.User", "User")
                        .WithOne()
                        .HasForeignKey("BenhaScooters.Domain.Drivers.DriverStats", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BenhaScooters.Domain.Drivers.DriverStatus", b =>
                {
                    b.HasOne("BenhaScooters.Domain.Users.User", "User")
                        .WithOne()
                        .HasForeignKey("BenhaScooters.Domain.Drivers.DriverStatus", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BenhaScooters.Domain.Drivers.DriverWallet", b =>
                {
                    b.HasOne("BenhaScooters.Domain.Users.User", "Driver")
                        .WithOne()
                        .HasForeignKey("BenhaScooters.Domain.Drivers.DriverWallet", "DriverUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("BenhaScooters.Domain.Drivers.WalletTopUpRequest", b =>
                {
                    b.HasOne("BenhaScooters.Domain.Users.User", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BenhaScooters.Domain.Drivers.DriverWallet", "Wallet")
                        .WithMany()
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("BenhaScooters.Domain.Drivers.WalletTransaction", b =>
                {
                    b.HasOne("BenhaScooters.Domain.Trips.Trip", "Trip")
                        .WithMany()
                        .HasForeignKey("TripId");

                    b.HasOne("BenhaScooters.Domain.Drivers.DriverWallet", null)
                        .WithMany("Transactions")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("BenhaScooters.Domain.Matching.DriverMatchAttempt", b =>
                {
                    b.HasOne("BenhaScooters.Domain.Drivers.DriverProfile", "DriverProfile")
                        .WithMany()
                        .HasForeignKey("DriverUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BenhaScooters.Domain.Matching.MatchingSession", "MatchingSession")
                        .WithMany("MatchAttempts")
                        .HasForeignKey("MatchingSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DriverProfile");

                    b.Navigation("MatchingSession");
                });

            modelBuilder.Entity("BenhaScooters.Domain.Matching.MatchingSession", b =>
                {
                    b.HasOne("BenhaScooters.Domain.TripRequests.TripRequest", "TripRequest")
                        .WithMany()
                        .HasForeignKey("TripRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TripRequest");
                });

            modelBuilder.Entity("BenhaScooters.Domain.Ratings.DriverRating", b =>
                {
                    b.HasOne("BenhaScooters.Domain.Trips.Trip", "Trip")
                        .WithMany()
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("BenhaScooters.Domain.Riders.RiderProfile", b =>
                {
                    b.HasOne("BenhaScooters.Domain.Users.User", "User")
                        .WithOne("RiderProfile")
                        .HasForeignKey("BenhaScooters.Domain.Riders.RiderProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("BenhaScooters.Domain.Riders.SavedAddress", "SavedAddresses", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.Property<string>("Label")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<double?>("Latitude")
                                .HasColumnType("double precision");

                            b1.Property<double?>("Longitude")
                                .HasColumnType("double precision");

                            b1.Property<int>("RiderUserId")
                                .HasColumnType("integer");

                            b1.HasKey("Id");

                            b1.HasIndex("RiderUserId", "Label")
                                .IsUnique();

                            b1.ToTable("RiderSavedAddresses", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("RiderUserId");
                        });

                    b.Navigation("SavedAddresses");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BenhaScooters.Domain.TripRequests.TripRequest", b =>
                {
                    b.HasOne("BenhaScooters.Domain.Drivers.DriverProfile", "MatchedDriverProfile")
                        .WithMany()
                        .HasForeignKey("MatchedDriverId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BenhaScooters.Domain.Riders.RiderProfile", "RiderProfile")
                        .WithMany("TripRequests")
                        .HasForeignKey("RiderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MatchedDriverProfile");

                    b.Navigation("RiderProfile");
                });

            modelBuilder.Entity("BenhaScooters.Domain.Trips.Trip", b =>
                {
                    b.HasOne("BenhaScooters.Domain.Drivers.DriverProfile", "DriverProfile")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BenhaScooters.Domain.Riders.RiderProfile", "RiderProfile")
                        .WithMany()
                        .HasForeignKey("RiderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BenhaScooters.Domain.TripRequests.TripRequest", "TripRequest")
                        .WithOne()
                        .HasForeignKey("BenhaScooters.Domain.Trips.Trip", "TripRequestId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("BenhaScooters.Domain.Trips.ValueObjects.TripPayment", "TripPayment", b1 =>
                        {
                            b1.Property<int>("TripId")
                                .HasColumnType("integer");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<string>("ExternalReference")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<string>("Method")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<decimal>("PaidAmount")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("TripId");

                            b1.ToTable("Trips");

                            b1.WithOwner()
                                .HasForeignKey("TripId");
                        });

                    b.Navigation("DriverProfile");

                    b.Navigation("RiderProfile");

                    b.Navigation("TripPayment");

                    b.Navigation("TripRequest");
                });

            modelBuilder.Entity("BenhaScooters.Domain.Trips.TripGpsPoint", b =>
                {
                    b.HasOne("BenhaScooters.Domain.Trips.TripRoute", "TripRoute")
                        .WithMany("TripGpsPoints")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TripRoute");
                });

            modelBuilder.Entity("BenhaScooters.Domain.Trips.TripRoute", b =>
                {
                    b.HasOne("BenhaScooters.Domain.Trips.Trip", "Trip")
                        .WithOne()
                        .HasForeignKey("BenhaScooters.Domain.Trips.TripRoute", "TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("BenhaScooters.Domain.Users.ExternalAuth", b =>
                {
                    b.HasOne("BenhaScooters.Domain.Users.User", "User")
                        .WithMany("ExternalAuths")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BenhaScooters.Domain.Users.RefreshToken", b =>
                {
                    b.HasOne("BenhaScooters.Domain.Users.User", null)
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BenhaScooters.Domain.Users.SmsLog", b =>
                {
                    b.HasOne("BenhaScooters.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("BenhaScooters.Domain.Users.SmsVerificationCode", b =>
                {
                    b.HasOne("BenhaScooters.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BenhaScooters.Domain.Users.UserDeviceToken", b =>
                {
                    b.HasOne("BenhaScooters.Domain.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BenhaScooters.Domain.Users.UserRole", b =>
                {
                    b.HasOne("BenhaScooters.Domain.Users.User", null)
                        .WithMany("Roles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BenhaScooters.Domain.Drivers.DriverWallet", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("BenhaScooters.Domain.Matching.MatchingSession", b =>
                {
                    b.Navigation("MatchAttempts");
                });

            modelBuilder.Entity("BenhaScooters.Domain.Riders.RiderProfile", b =>
                {
                    b.Navigation("TripRequests");
                });

            modelBuilder.Entity("BenhaScooters.Domain.Trips.TripRoute", b =>
                {
                    b.Navigation("TripGpsPoints");
                });

            modelBuilder.Entity("BenhaScooters.Domain.Users.User", b =>
                {
                    b.Navigation("DriverProfile");

                    b.Navigation("ExternalAuths");

                    b.Navigation("RefreshTokens");

                    b.Navigation("RiderProfile");

                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
