// <auto-generated />
using System;
using BenhaScooters.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BenhaScooters.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260121084156_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BenhaScooters.Domain.Drivers.DriverLocation", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<float?>("Heading")
                        .HasColumnType("real");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geography (point)");

                    b.Property<float?>("Speed")
                        .HasColumnType("real");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId");

                    b.HasIndex("Location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "GIST");

                    b.HasIndex("Timestamp");

                    b.ToTable("DriverLocations", (string)null);
                });

            modelBuilder.Entity("BenhaScooters.Domain.Drivers.DriverProfile", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OnboardingStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("UserId");

                    b.HasIndex("OnboardingStatus");

                    b.ToTable("DriverProfiles", (string)null);
                });

            modelBuilder.Entity("BenhaScooters.Domain.Drivers.DriverStats", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<decimal>("AverageRating")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)");

                    b.Property<int>("CancelledTrips")
                        .HasColumnType("integer");

                    b.Property<int>("CompletedTrips")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentStreak")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastOnlineAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastStreakDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastTripAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan>("TotalOnlineTime")
                        .HasColumnType("interval");

                    b.Property<int>("TotalRatings")
                        .HasColumnType("integer");

                    b.Property<int>("TotalTrips")
                        .HasColumnType("integer");

                    b.HasKey("UserId");

                    b.HasIndex("AverageRating");

                    b.HasIndex("CompletedTrips");

                    b.ToTable("DriverStats", (string)null);
                });

            modelBuilder.Entity("BenhaScooters.Domain.Drivers.DriverStatus", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int?>("CurrentTripId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastStatusChange")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("OnlineSessionStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.HasIndex("Status");

                    b.HasIndex("Status", "UserId");

                    b.ToTable("DriverStatuses", (string)null);
                });

            modelBuilder.Entity("BenhaScooters.Domain.Matching.DriverMatchAttempt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("DistanceToPickup")
                        .HasPrecision(8, 3)
                        .HasColumnType("double precision");

                    b.Property<decimal>("DriverScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<int>("DriverUserId")
                        .HasColumnType("integer");

                    b.Property<double>("EstimatedArrivalTime")
                        .HasPrecision(5, 2)
                        .HasColumnType("double precision");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MatchingSessionId")
                        .HasColumnType("integer");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("DriverUserId");

                    b.HasIndex("MatchingSessionId");

                    b.HasIndex("Status");

                    b.ToTable("DriverMatchAttempts");
                });

            modelBuilder.Entity("BenhaScooters.Domain.Matching.MatchingSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentRound")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NumberOfRounds")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<int[]>("OffersPerRound")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TripRequestId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Status");

                    b.HasIndex("TripRequestId")
                        .IsUnique();

                    b.ToTable("MatchingSessions");
                });

            modelBuilder.Entity("BenhaScooters.Domain.Riders.RiderProfile", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<decimal>("AverageRating")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DefaultPaymentMethodId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastTripAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PreferredName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("TotalRatings")
                        .HasColumnType("integer");

                    b.Property<int>("TotalTrips")
                        .HasColumnType("integer");

                    b.HasKey("UserId");

                    b.ToTable("RiderProfiles", (string)null);
                });

            modelBuilder.Entity("BenhaScooters.Domain.TripRequests.TripRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DropoffAddress")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Point>("DropoffLocation")
                        .IsRequired()
                        .HasColumnType("geography (point)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("MatchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("MatchedDriverUserId")
                        .HasColumnType("integer");

                    b.Property<string>("PickupAddress")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Point>("PickupLocation")
                        .IsRequired()
                        .HasColumnType("geography (point)");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RiderUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MatchedDriverUserId");

                    b.HasIndex("RequestedAt");

                    b.HasIndex("RiderUserId");

                    b.HasIndex("Status");

                    b.ToTable("TripRequests");
                });

            modelBuilder.Entity("BenhaScooters.Domain.Trips.Trip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DriverArrivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DriverUserId")
                        .HasColumnType("integer");

                    b.Property<string>("DropoffAddress")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Point>("DropoffLocation")
                        .IsRequired()
                        .HasColumnType("geography (point)");

                    b.Property<string>("PickupAddress")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Point>("PickupLocation")
                        .IsRequired()
                        .HasColumnType("geography (point)");

                    b.Property<int>("RiderUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DriverUserId");

                    b.HasIndex("RiderUserId");

                    b.HasIndex("Status");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("BenhaScooters.Domain.Trips.TripGpsPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geography (point)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TripId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "GIST");

                    b.HasIndex("Timestamp");

                    b.HasIndex("TripId");

                    b.ToTable("TripGpsPoints");
                });

            modelBuilder.Entity("BenhaScooters.Domain.Trips.TripRoute", b =>
                {
                    b.Property<int>("TripId")
                        .HasColumnType("integer");

                    b.Property<LineString>("Path")
                        .IsRequired()
                        .HasColumnType("geometry (LineString, 4326)");

                    b.HasKey("TripId");

                    b.ToTable("TripRoutes", (string)null);
                });

            modelBuilder.Entity("BenhaScooters.Domain.Users.ExternalAuth", b =>
                {
                    b.Property<string>("Provider")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ProviderUserId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Provider", "ProviderUserId");

                    b.HasIndex("UserId");

                    b.ToTable("ExternalAuths", (string)null);
                });

            modelBuilder.Entity("BenhaScooters.Domain.Users.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("BenhaScooters.Domain.Users.SmsVerificationCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Code");

                    b.HasIndex("UserId", "PhoneNumber", "CreatedAt");

                    b.ToTable("SmsVerificationCodes");
                });

            modelBuilder.Entity("BenhaScooters.Domain.Users.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EmailNormalized")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PhoneNumberNormalized")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("PhoneNumberVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EmailNormalized");

                    b.HasIndex("PhoneNumberNormalized");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BenhaScooters.Domain.Users.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("BenhaScooters.Domain.Drivers.DriverLocation", b =>
                {
                    b.HasOne("BenhaScooters.Domain.Users.User", "User")
                        .WithOne()
                        .HasForeignKey("BenhaScooters.Domain.Drivers.DriverLocation", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BenhaScooters.Domain.Drivers.DriverProfile", b =>
                {
                    b.HasOne("BenhaScooters.Domain.Users.User", "User")
                        .WithOne()
                        .HasForeignKey("BenhaScooters.Domain.Drivers.DriverProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("BenhaScooters.Domain.Drivers.DriverPersonalInfo", "PersonalInfo", b1 =>
                        {
                            b1.Property<int>("DriverProfileUserId")
                                .HasColumnType("integer");

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("PersonalInfo_Address");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("PersonalInfo_City");

                            b1.Property<DateOnly>("DateOfBirth")
                                .HasColumnType("date")
                                .HasColumnName("PersonalInfo_DateOfBirth");

                            b1.Property<string>("EmergencyContactName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("PersonalInfo_EmergencyContactName");

                            b1.Property<string>("EmergencyContactPhone")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("PersonalInfo_EmergencyContactPhone");

                            b1.Property<string>("FullName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("PersonalInfo_FullName");

                            b1.Property<string>("NationalId")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("PersonalInfo_NationalId");

                            b1.HasKey("DriverProfileUserId");

                            b1.ToTable("DriverProfiles");

                            b1.WithOwner()
                                .HasForeignKey("DriverProfileUserId");
                        });

                    b.OwnsOne("BenhaScooters.Domain.Drivers.DriverVehicleInfo", "Vehicle", b1 =>
                        {
                            b1.Property<int>("DriverProfileUserId")
                                .HasColumnType("integer");

                            b1.Property<string>("Brand")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("Vehicle_Brand");

                            b1.Property<string>("Color")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("Vehicle_Color");

                            b1.Property<string>("LicensePlate")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Vehicle_LicensePlate");

                            b1.Property<string>("Model")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("Vehicle_Model");

                            b1.Property<string>("VIN")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Vehicle_VIN");

                            b1.Property<string>("VehicleType")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Vehicle_Type");

                            b1.Property<int>("Year")
                                .HasColumnType("integer")
                                .HasColumnName("Vehicle_Year");

                            b1.HasKey("DriverProfileUserId");

                            b1.ToTable("DriverProfiles");

                            b1.WithOwner()
                                .HasForeignKey("DriverProfileUserId");
                        });

                    b.OwnsMany("BenhaScooters.Domain.Drivers.DriverDocument", "Documents", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<int>("DriverUserId")
                                .HasColumnType("integer");

                            b1.Property<DateOnly?>("ExpiryDate")
                                .HasColumnType("date");

                            b1.Property<string>("ImageUrl")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<DateTime>("UploadedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("Id");

                            b1.HasIndex("DriverUserId", "Type")
                                .IsUnique();

                            b1.ToTable("DriverDocuments", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("DriverUserId");
                        });

                    b.Navigation("Documents");

                    b.Navigation("PersonalInfo");

                    b.Navigation("User");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("BenhaScooters.Domain.Drivers.DriverStats", b =>
                {
                    b.HasOne("BenhaScooters.Domain.Users.User", "User")
                        .WithOne()
                        .HasForeignKey("BenhaScooters.Domain.Drivers.DriverStats", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BenhaScooters.Domain.Drivers.DriverStatus", b =>
                {
                    b.HasOne("BenhaScooters.Domain.Users.User", "User")
                        .WithOne()
                        .HasForeignKey("BenhaScooters.Domain.Drivers.DriverStatus", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BenhaScooters.Domain.Matching.DriverMatchAttempt", b =>
                {
                    b.HasOne("BenhaScooters.Domain.Drivers.DriverProfile", "DriverProfile")
                        .WithMany()
                        .HasForeignKey("DriverUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BenhaScooters.Domain.Matching.MatchingSession", "MatchingSession")
                        .WithMany("MatchAttempts")
                        .HasForeignKey("MatchingSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DriverProfile");

                    b.Navigation("MatchingSession");
                });

            modelBuilder.Entity("BenhaScooters.Domain.Matching.MatchingSession", b =>
                {
                    b.HasOne("BenhaScooters.Domain.TripRequests.TripRequest", "TripRequest")
                        .WithMany()
                        .HasForeignKey("TripRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TripRequest");
                });

            modelBuilder.Entity("BenhaScooters.Domain.Riders.RiderProfile", b =>
                {
                    b.HasOne("BenhaScooters.Domain.Users.User", "User")
                        .WithOne()
                        .HasForeignKey("BenhaScooters.Domain.Riders.RiderProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("BenhaScooters.Domain.Riders.SavedAddress", "SavedAddresses", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.Property<string>("Label")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<double?>("Latitude")
                                .HasColumnType("double precision");

                            b1.Property<double?>("Longitude")
                                .HasColumnType("double precision");

                            b1.Property<int>("RiderUserId")
                                .HasColumnType("integer");

                            b1.HasKey("Id");

                            b1.HasIndex("RiderUserId", "Label")
                                .IsUnique();

                            b1.ToTable("RiderSavedAddresses", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("RiderUserId");
                        });

                    b.Navigation("SavedAddresses");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BenhaScooters.Domain.TripRequests.TripRequest", b =>
                {
                    b.HasOne("BenhaScooters.Domain.Drivers.DriverProfile", "MatchedDriverProfile")
                        .WithMany()
                        .HasForeignKey("MatchedDriverUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BenhaScooters.Domain.Riders.RiderProfile", "RiderProfile")
                        .WithMany()
                        .HasForeignKey("RiderUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("BenhaScooters.Domain.Trips.ValueObjects.FareEstimate", "FinalFare", b1 =>
                        {
                            b1.Property<int>("TripRequestId")
                                .HasColumnType("integer");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("FinalFare_Amount");

                            b1.Property<double>("Distance")
                                .HasColumnType("double precision")
                                .HasColumnName("FinalFare_Distance");

                            b1.Property<double>("Time")
                                .HasColumnType("double precision")
                                .HasColumnName("FinalFare_Time");

                            b1.HasKey("TripRequestId");

                            b1.ToTable("TripRequests");

                            b1.WithOwner()
                                .HasForeignKey("TripRequestId");
                        });

                    b.Navigation("FinalFare")
                        .IsRequired();

                    b.Navigation("MatchedDriverProfile");

                    b.Navigation("RiderProfile");
                });

            modelBuilder.Entity("BenhaScooters.Domain.Trips.Trip", b =>
                {
                    b.HasOne("BenhaScooters.Domain.Drivers.DriverProfile", "DriverProfile")
                        .WithMany()
                        .HasForeignKey("DriverUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BenhaScooters.Domain.Riders.RiderProfile", "RiderProfile")
                        .WithMany()
                        .HasForeignKey("RiderUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("BenhaScooters.Domain.Trips.ValueObjects.FareEstimate", "FinalFare", b1 =>
                        {
                            b1.Property<int>("TripId")
                                .HasColumnType("integer");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("FinalFare_Amount");

                            b1.Property<double>("Distance")
                                .HasColumnType("double precision")
                                .HasColumnName("FinalFare_Distance");

                            b1.Property<double>("Time")
                                .HasColumnType("double precision")
                                .HasColumnName("FinalFare_Time");

                            b1.HasKey("TripId");

                            b1.ToTable("Trips");

                            b1.WithOwner()
                                .HasForeignKey("TripId");
                        });

                    b.OwnsOne("BenhaScooters.Domain.Trips.ValueObjects.TripFare", "TripFare", b1 =>
                        {
                            b1.Property<int>("TripId")
                                .HasColumnType("integer");

                            b1.Property<decimal>("BaseFare")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<decimal>("DistanceFare")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<decimal>("DurationFare")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<decimal>("SurgeMultiplier")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("TotalFare")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("TotalFare");

                            b1.HasKey("TripId");

                            b1.ToTable("Trips");

                            b1.WithOwner()
                                .HasForeignKey("TripId");
                        });

                    b.OwnsOne("BenhaScooters.Domain.Trips.ValueObjects.TripPayment", "TripPayment", b1 =>
                        {
                            b1.Property<int>("TripId")
                                .HasColumnType("integer");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<string>("ExternalReference")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<string>("Method")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<decimal>("PaidAmount")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("TripId");

                            b1.ToTable("Trips");

                            b1.WithOwner()
                                .HasForeignKey("TripId");
                        });

                    b.Navigation("DriverProfile");

                    b.Navigation("FinalFare")
                        .IsRequired();

                    b.Navigation("RiderProfile");

                    b.Navigation("TripFare");

                    b.Navigation("TripPayment");
                });

            modelBuilder.Entity("BenhaScooters.Domain.Trips.TripGpsPoint", b =>
                {
                    b.HasOne("BenhaScooters.Domain.Trips.TripRoute", "TripRoute")
                        .WithMany("TripGpsPoints")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TripRoute");
                });

            modelBuilder.Entity("BenhaScooters.Domain.Trips.TripRoute", b =>
                {
                    b.HasOne("BenhaScooters.Domain.Trips.Trip", "Trip")
                        .WithOne()
                        .HasForeignKey("BenhaScooters.Domain.Trips.TripRoute", "TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("BenhaScooters.Domain.Users.ExternalAuth", b =>
                {
                    b.HasOne("BenhaScooters.Domain.Users.User", "User")
                        .WithMany("ExternalAuths")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BenhaScooters.Domain.Users.RefreshToken", b =>
                {
                    b.HasOne("BenhaScooters.Domain.Users.User", null)
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BenhaScooters.Domain.Users.SmsVerificationCode", b =>
                {
                    b.HasOne("BenhaScooters.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BenhaScooters.Domain.Users.UserRole", b =>
                {
                    b.HasOne("BenhaScooters.Domain.Users.User", null)
                        .WithMany("Roles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BenhaScooters.Domain.Matching.MatchingSession", b =>
                {
                    b.Navigation("MatchAttempts");
                });

            modelBuilder.Entity("BenhaScooters.Domain.Trips.TripRoute", b =>
                {
                    b.Navigation("TripGpsPoints");
                });

            modelBuilder.Entity("BenhaScooters.Domain.Users.User", b =>
                {
                    b.Navigation("ExternalAuths");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
